### ISSUE TITLE
坐标

### ISSUE THREAD

**Issue by cqray1990** [yjmm10/SealGenForOCR#1]

**Comment by yjmm10** [comment]
是指什么七个坐标
程序中 默认标注的是14个点的坐标，环形文字上方7个点，下方7个点。这样做也是为了矫正时可以通过TPS算法进行矫正。

**Comment by cqray1990** [comment]
。。。

**Comment by yjmm10** [comment]
图片没上传成功，这个是14个点，这些点因为计算时候没办法完全贴合到弯曲文本上，会有些变形，圆形则不会有这个问题。
这里简单说下原理，就是根据椭圆的角度进行七个点的划分，但因为椭圆的等间距旋转角度对应的弧长会不一致，导致最后的标注点有所偏差。对于圆则没有这个问题

**Comment by cqray1990** [comment]
。。。。。
